import type { Question } from "@/lib/types";

export const quizQuestions: Question[] = [
  {
    id: "q1",
    title: "Which best describes your current AI experience?",
    type: "single",
    options: [
      "I barely know what AI tools are",
      "I have tried ChatGPT a few times",
      "I use ChatGPT, Claude, or another AI tool regularly",
      "I use AI in actual business workflows",
      "I have built automations, agents, or AI systems",
    ],
  },
  {
    id: "q2",
    title: "Which AI or automation tools have you personally used? Select all that apply.",
    type: "multi",
    options: [
      "ChatGPT",
      "Claude",
      "Gemini",
      "Perplexity",
      "Midjourney or other image AI tools",
      "Zapier",
      "Make",
      "n8n",
      "Custom GPTs",
      "AI voice tools",
      "None of these",
    ],
  },
  {
    id: "q3",
    title: "How confident are you explaining what an LLM is?",
    type: "single",
    options: [
      "Not confident at all",
      "I have heard the term, but I could not explain it",
      "I can explain it in simple terms",
      "I understand it pretty well",
      "I could teach it to someone else",
    ],
  },
  {
    id: "q4",
    title: "Do you understand the difference between AI and automation?",
    type: "single",
    options: ["No", "Somewhat", "Yes, but not deeply", "Yes, and I use both", "Yes, and I know when to use each one"],
  },
  {
    id: "q5",
    title: "When you use ChatGPT, Claude, or another AI tool, how do you usually prompt it?",
    type: "single",
    options: [
      "I ask short basic questions",
      "I give it some context",
      "I include the goal, background, and desired format",
      "I include examples, constraints, and clear instructions",
      "I use reusable prompt templates or workflows",
    ],
  },
  {
    id: "q6",
    title: "Can you make AI write in your brand voice or company style?",
    type: "single",
    options: [
      "No",
      "I have tried, but results are inconsistent",
      "Somewhat",
      "Yes, pretty well",
      "Yes, and I have reusable brand prompts or examples",
    ],
  },
  {
    id: "q7",
    title: "When AI gives you a weak answer, what do you usually do?",
    type: "single",
    options: [
      "Give up",
      "Ask again with almost the same request",
      "Add more context",
      "Tell it what was wrong and improve the prompt",
      "Use a structured revision process",
    ],
  },
  {
    id: "q8",
    title: "Do you use AI to critique, improve, or pressure-test its own output?",
    type: "single",
    options: ["Never", "Rarely", "Sometimes", "Often", "Yes, this is part of my normal workflow"],
  },
  {
    id: "q9",
    title: "Do you know why AI sometimes makes things up or gives confident wrong answers?",
    type: "single",
    options: [
      "No",
      "I have heard this happens",
      "I understand the basic idea",
      "I know how to reduce the risk",
      "I have verification workflows in place",
    ],
  },
  {
    id: "q10",
    title: "When do you verify AI output?",
    type: "single",
    options: [
      "I usually do not verify it",
      "Only if the answer seems suspicious",
      "For important facts",
      "For anything public-facing or business-critical",
      "I have clear verification rules",
    ],
  },
  {
    id: "q11",
    title: "Do you know when NOT to use AI?",
    type: "single",
    options: [
      "No",
      "Somewhat",
      "Yes, for obvious sensitive situations",
      "Yes, I have clear boundaries",
      "Yes, and my team follows those boundaries",
    ],
  },
  {
    id: "q12",
    title: "Where do you currently spend too much time? Select all that apply.",
    type: "multi",
    options: [
      "Email / inbox",
      "Content creation",
      "Lead follow-up",
      "Customer service",
      "Admin work",
      "Research",
      "Hiring / training",
      "Reporting",
      "Operations",
      "Meetings",
      "Other",
    ],
  },
  {
    id: "q13",
    title: "What would be most valuable for your business right now? Select up to 2.",
    type: "multi",
    maxSelections: 2,
    options: ["Save time", "Save money", "Make more money", "Make better/faster decisions", "Reduce errors", "Improve team execution"],
  },
  {
    id: "q14",
    title: "Which area would you most like AI to improve first?",
    type: "single",
    options: [
      "Sales",
      "Marketing",
      "Content",
      "Customer support",
      "Operations",
      "Admin",
      "Finance / reporting",
      "Hiring / team training",
      "Personal productivity",
    ],
  },
  {
    id: "q15",
    title: "Do you know which business process AI should improve first?",
    type: "single",
    options: ["No idea", "I have a few ideas", "I know the general area", "I know the exact workflow", "I already have a prioritized AI roadmap"],
  },
  {
    id: "q16",
    title: "Have you ever connected two apps together automatically?",
    type: "single",
    options: ["No", "I have seen it done", "I have used Zapier, Make, or something similar", "I have built simple workflows", "I have built advanced workflows"],
  },
  {
    id: "q17",
    title: "Do you understand what an API is?",
    type: "single",
    options: ["No", "I have heard of it", "I understand the basic idea", "I understand it pretty well", "I have used APIs before"],
  },
  {
    id: "q18",
    title: "Do you understand the difference between paying for ChatGPT and paying for API usage?",
    type: "single",
    options: ["No", "I have heard there is a difference", "Somewhat", "Yes", "Yes, and I can roughly estimate usage cost"],
  },
  {
    id: "q19",
    title: "Do you have rules for what your team can paste into AI tools?",
    type: "single",
    options: ["No", "Not yet, but we need them", "Informal rules", "Written rules", "Written rules plus team training"],
  },
  {
    id: "q20",
    title: "Which data would you be comfortable pasting into AI? Select all that apply.",
    type: "multi",
    options: [
      "Public website copy",
      "Internal SOPs",
      "Customer emails",
      "Financial data",
      "Passwords / API keys",
      "Legal documents",
      "Private client data",
      "None without review",
    ],
  },
];
