import type { CategoryKey, Question, QuestionOption } from "@/lib/types";

function option(id: string, label: string, points: number, category: CategoryKey): QuestionOption {
  return { id, label, points, category };
}

function single(id: string, title: string, category: CategoryKey, labels: Array<[string, number]>): Question {
  return {
    id,
    title,
    type: "single",
    options: labels.map(([label, points], index) => option(`${id}_${String.fromCharCode(97 + index)}`, label, points, category)),
  };
}

export const quizQuestions: Question[] = [
  single("q1", "How would you honestly describe your AI experience right now?", "aiBasics", [
    ["I've heard about AI but I haven't really used it.", 0],
    ["I've tried ChatGPT once or twice out of curiosity.", 2],
    ["I use ChatGPT or Claude a few times a week for personal stuff.", 4],
    ["I use AI most days, including for real business work.", 7],
    ["I've built or commissioned automations or AI workflows that run without me.", 10],
  ]),
  single("q2", "When someone says \"LLM,\" what's your honest reaction?", "aiBasics", [
    ["No idea what that means.", 0],
    ["I've heard the term but couldn't explain it.", 2],
    ["I roughly know - it's the thing behind ChatGPT.", 5],
    ["I could explain it to a friend in plain English.", 8],
    ["I can explain LLMs, transformers, and tokens, and the differences between models.", 10],
  ]),
  single("q3", "What is a \"token\" in AI?", "aiBasics", [
    ["I don't know.", 0],
    ["A word.", 1],
    ["A chunk of text, usually a few characters; how the AI reads and writes.", 10],
    ["A type of cryptocurrency used to pay for AI.", 0],
    ["The login key for the API.", 0],
  ]),
  single("q4", "How would you explain the difference between AI and automation?", "aiBasics", [
    ["They're the same thing.", 0],
    ["I'm not sure.", 1],
    ["AI is newer and smarter; automation is older.", 3],
    ["Automation follows fixed rules; AI uses judgment on unstructured input.", 10],
  ]),
  {
    id: "q5",
    title: "Which of these have you actually used yourself? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q5_a", "ChatGPT (free)", 1, "aiBasics"),
      option("q5_b", "ChatGPT (paid: Plus, Team, or Enterprise)", 3, "aiBasics"),
      option("q5_c", "Claude (free or paid)", 3, "aiBasics"),
      option("q5_d", "Gemini", 1, "aiBasics"),
      option("q5_e", "Microsoft Copilot", 2, "aiBasics"),
      option("q5_f", "Perplexity", 2, "aiBasics"),
      option("q5_g", "A voice AI tool (Vapi, Bland, Retell, ElevenLabs, etc.)", 3, "automationTools"),
      option("q5_h", "An automation tool (Zapier, Make, n8n) connected to AI", 3, "automationTools"),
      option("q5_i", "None of the above", 0, "aiBasics"),
    ],
  },
  single("q6", "About how often do you use AI in a typical week?", "aiBasics", [
    ["Never or almost never.", 0],
    ["Once or twice a week.", 2],
    ["A few times a week.", 4],
    ["Daily - at least 5 days out of 7.", 7],
    ["Multiple times a day, every day.", 10],
  ]),
  single("q7", "When you ask AI for something and the output is generic or weak, what do you usually do?", "prompting", [
    ["I assume AI just isn't useful for this and stop.", 0],
    ["I try the same prompt in a different tool.", 3],
    ["I rewrite the prompt with more context and try again.", 7],
    ["I iterate - add context, examples, constraints, ask it to critique its own output, then refine.", 10],
  ]),
  single("q8", "How long is a typical prompt you send to AI?", "prompting", [
    ["A few words, like a Google search.", 0],
    ["One short sentence.", 2],
    ["Two or three sentences with some context.", 5],
    ["A full paragraph or more, with role, context, task, and constraints.", 8],
    ["A structured prompt template I've saved and reuse.", 10],
  ]),
  {
    id: "q9",
    title: "Which of these do you actually do when prompting AI? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q9_a", "Tell the AI who it should be (a role or persona).", 2, "prompting"),
      option("q9_b", "Give it background context about my business or audience.", 2, "prompting"),
      option("q9_c", "Paste in examples of what good looks like.", 3, "prompting"),
      option("q9_d", "Specify length, format, or tone.", 2, "prompting"),
      option("q9_e", "Ask it to ask me clarifying questions first.", 2, "prompting"),
      option("q9_f", "Ask for multiple variations, then pick the best.", 2, "prompting"),
      option("q9_g", "Ask it to critique its own answer and improve it.", 2, "prompting"),
      option("q9_h", "None of these - I just ask my question.", 0, "prompting"),
    ],
  },
  single("q10", "Do you save or reuse prompts that worked well?", "prompting", [
    ["I don't even know what that means.", 0],
    ["No, I write a new one every time.", 2],
    ["I copy and paste from old chats sometimes.", 5],
    ["I have a prompt library I maintain (Notion, Google Doc, etc.).", 10],
  ]),
  single("q11", "When AI gives you a specific number, statistic, or citation, what do you do?", "verification", [
    ["I trust it and use it.", 0],
    ["I'd probably trust it for low-stakes stuff.", 2],
    ["I verify if it feels important.", 5],
    ["I verify anything specific by default - names, numbers, citations, claims.", 10],
  ]),
  single("q12", "What does \"hallucination\" mean in the context of AI?", "verification", [
    ["I don't know.", 0],
    ["When the AI crashes or errors out.", 1],
    ["When the AI confidently makes something up that isn't true.", 10],
    ["When the AI gets confused and asks for clarification.", 2],
  ]),
  single("q13", "You ask AI for \"5 recent studies on X.\" It gives you 5 with titles, authors, and dates. What do you do?", "verification", [
    ["Use them in my work.", 0],
    ["Skim them and pick the best one.", 2],
    ["Check that at least the first one is real.", 5],
    ["Verify every single one exists before citing any of them.", 10],
  ]),
  single("q14", "Have you ever caught AI giving you something materially wrong (a wrong number, a fake quote, a non-existent tool feature, etc.)?", "verification", [
    ["No, never noticed.", 0],
    ["Maybe once or twice.", 3],
    ["Yes, multiple times - I expect it now.", 8],
    ["Yes, and I now have a habit of checking everything specific.", 10],
  ]),
  single("q15", "How clearly can you name the #1 highest-ROI place AI could help your business right now?", "businessStrategy", [
    ["I have no idea.", 0],
    ["I have a vague sense but couldn't be specific.", 2],
    ["I have 2 or 3 candidates but haven't decided.", 5],
    ["I know exactly - specific task, specific hours saved or revenue gained.", 10],
  ]),
  {
    id: "q16",
    title: "Which of these are real, recurring problems in your business right now? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q16_a", "Slow follow-up with new leads.", 2, "businessStrategy"),
      option("q16_b", "Too much time spent on email.", 2, "businessStrategy"),
      option("q16_c", "Inconsistent content output (blog, social, email).", 2, "businessStrategy"),
      option("q16_d", "Meeting notes and action items never getting captured.", 2, "businessStrategy"),
      option("q16_e", "Customer support eating team time.", 2, "businessStrategy"),
      option("q16_f", "Manual data entry or cleanup.", 2, "businessStrategy"),
      option("q16_g", "Proposals or quotes taking too long to send.", 2, "businessStrategy"),
      option("q16_h", "None of these.", 0, "businessStrategy"),
    ],
  },
  single("q17", "How would you rate your current AI follow-up speed for new inbound leads?", "businessStrategy", [
    ["We don't follow up automatically - it's manual or it doesn't happen.", 0],
    ["We follow up manually within a few hours during business days.", 3],
    ["We have basic automated email follow-up within 30 minutes.", 6],
    ["We respond in under 5 minutes, 24/7, with AI-assisted personalization or a voice agent.", 10],
  ]),
  single("q18", "About how much of your weekly content (email, social, blog) is currently AI-assisted in some way?", "businessStrategy", [
    ["None.", 0],
    ["Less than 25%.", 3],
    ["About half.", 6],
    ["75% or more - AI is in the loop on almost everything we publish.", 10],
  ]),
  single("q19", "What's your view on building a \"custom AI\" for your business?", "businessStrategy", [
    ["I think I need one.", 3],
    ["I have no opinion.", 2],
    ["I'd consider it if the ROI was clear.", 6],
    ["Probably overkill - off-the-shelf tools plus good prompts will solve most things.", 10],
  ]),
  single("q20", "Do you currently use any automation platform (Zapier, Make, n8n, etc.)?", "automationTools", [
    ["I don't know what those are.", 0],
    ["I've heard of them but don't use them.", 2],
    ["I have a few basic Zaps or scenarios running.", 5],
    ["I have multi-step automated workflows running in production.", 8],
    ["I have AI-in-the-loop workflows (automation tool calling an AI model).", 10],
  ]),
  single("q21", "How would you describe your familiarity with AI agents (AI that takes actions, not just answers)?", "automationTools", [
    ["Never heard of them.", 0],
    ["Heard the term, don't really know what they do.", 2],
    ["I understand the concept - AI that can browse, send, book, act.", 5],
    ["I've tried one or used a product that includes an agent.", 8],
    ["I have agents running in my business with human review steps.", 10],
  ]),
  single("q22", "Voice AI for lead calling / appointment booking - where are you?", "automationTools", [
    ["Never considered it.", 0],
    ["Considered it, haven't acted.", 3],
    ["Tested or piloted a voice AI tool.", 6],
    ["Voice AI is live in my business handling real calls.", 10],
  ]),
  {
    id: "q23",
    title: "Which of these AI categories do you have actually running in your business (not tried once)? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q23_a", "AI-drafted email replies", 3, "automationTools"),
      option("q23_b", "AI meeting summaries with action items", 2, "automationTools"),
      option("q23_c", "AI-generated first-draft content", 2, "automationTools"),
      option("q23_d", "AI-powered lead routing or qualification", 3, "automationTools"),
      option("q23_e", "Voice AI answering or making calls", 3, "automationTools"),
      option("q23_f", "AI customer support (chat or email)", 3, "automationTools"),
      option("q23_g", "AI data cleanup or reporting", 2, "automationTools"),
      option("q23_h", "None yet.", 0, "automationTools"),
    ],
  },
  single("q24", "Does your team have a written policy on what data can and can't go into AI tools?", "teamPrivacyImplementation", [
    ["No, and I haven't thought about it.", 0],
    ["No, but I've been meaning to.", 2],
    ["Informal - everyone kind of knows.", 4],
    ["Yes, a written one-pager every team member has read.", 10],
  ]),
  {
    id: "q25",
    title: "Which of these have you (or someone on your team) ever pasted into a free AI chat? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q25_a", "Client confidential information or contracts under NDA.", -3, "teamPrivacyImplementation"),
      option("q25_b", "Credit card or bank account numbers.", -3, "teamPrivacyImplementation"),
      option("q25_c", "Health information / PHI.", -3, "teamPrivacyImplementation"),
      option("q25_d", "Login credentials, passwords, or API keys.", -3, "teamPrivacyImplementation"),
      option("q25_e", "Proprietary source code from a client.", -2, "teamPrivacyImplementation"),
      option("q25_f", "Internal trade secrets or unannounced plans.", -2, "teamPrivacyImplementation"),
      option("q25_g", "None of these - we're careful.", 10, "teamPrivacyImplementation"),
    ],
  },
  single("q26", "What tier of AI tool does your team primarily use for company work?", "teamPrivacyImplementation", [
    ["Free tiers / personal accounts.", 1],
    ["Mix of free and paid personal accounts.", 3],
    ["Paid consumer tier (ChatGPT Plus, Claude Pro).", 6],
    ["Business / Team / Enterprise tier with no-training-on-data commitments.", 10],
  ]),
  single("q27", "How is your team trained on AI usage?", "teamPrivacyImplementation", [
    ["They're not - everyone figures it out themselves.", 0],
    ["We've shared a few articles or videos.", 3],
    ["We've done at least one structured team training session.", 6],
    ["We have ongoing training, a shared prompt library, and a designated AI stack owner.", 10],
  ]),
];
