import type { CategoryKey, Question, QuestionOption } from "@/lib/types";

function option(id: string, label: string, category: CategoryKey, earnsPoints = false): QuestionOption {
  return { id, label, points: earnsPoints ? 10 : 0, category };
}

function single(id: string, title: string, category: CategoryKey, labels: string[], scoringIndex: number): Question {
  return {
    id,
    title,
    type: "single",
    options: labels.map((label, index) => option(`${id}_${String.fromCharCode(97 + index)}`, label, category, index === scoringIndex)),
  };
}

export const quizQuestions: Question[] = [
  single(
    "q1",
    'You receive a customer message: "I was charged twice for order #4471 and nobody answered my two emails." Which AI-drafted reply is best?',
    "prompting",
    [
      '"Thank you for your feedback! We value your business and will look into it. Have a great day!"',
      '"Dear valued customer, we apologize for any inconvenience. Your satisfaction is our top priority."',
      "\"I'm sorry about the double charge on #4471 and that your earlier emails went unanswered. I've flagged the duplicate for refund and will confirm by email within 24 hours.\"",
      "\"We've received your message about #4471. Please allow 5-7 business days for a response.\"",
    ],
<<<<<<< HEAD
  },
  single("q6", "Which of these best describes how AI tools are priced?", "aiBasics", [
    ["AI is free — the tools are just like Google.", 0],
    ["Most tools charge a fixed monthly fee, and that's it.", 3],
    ["Paid tiers exist, but I don't know how API or usage-based pricing works.", 5],
    ["Subscription tiers for chat, plus pay-per-token for API and automation usage.", 8],
    ["Subscriptions for humans, token-based pricing for API calls, and wrapper tools that mark up the underlying model cost.", 10],
  ]),
  single("q7", "When you ask AI for something and the output is generic or weak, what do you usually do?", "prompting", [
    ["I assume AI just isn't useful for this and stop.", 0],
    ["I try the same prompt in a different tool.", 3],
    ["I rewrite the prompt with more context and try again.", 7],
    ["I explain to AI in simple words what I want and ask it to create the best prompt for me.", 8],
    ["I iterate - add context, examples, constraints, ask it to critique its own output, then refine.", 10],
  ]),
  single("q8", "How long is a typical prompt you send to AI?", "prompting", [
    ["A few words, like a Google search.", 0],
    ["One short sentence.", 2],
    ["Two or three sentences with some context.", 5],
    ["A full paragraph or more, with role, context, task, and constraints.", 8],
    ["A structured prompt template I've saved and reuse.", 10],
  ]),
  {
    id: "q9",
    title: "Which of these do you actually do when prompting AI? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q9_a", "Tell the AI who it should be (a role or persona).", 2, "prompting"),
      option("q9_b", "Give it background context about my business or audience.", 2, "prompting"),
      option("q9_c", "Paste in examples of what good looks like.", 3, "prompting"),
      option("q9_d", "Specify length, format, or tone.", 2, "prompting"),
      option("q9_e", "Ask it to ask me clarifying questions first.", 2, "prompting"),
      option("q9_f", "Ask for multiple variations, then pick the best.", 2, "prompting"),
      option("q9_g", "Ask it to critique its own answer and improve it.", 2, "prompting"),
      option("q9_h", "None of these - I just ask my question.", 0, "prompting"),
    ],
  },
  single("q10", "Do you save or reuse prompts that worked well?", "prompting", [
    ["I don't even know what that means.", 0],
    ["No, I write a new one every time.", 2],
    ["I copy and paste from old chats sometimes.", 5],
    ["I have a prompt library I maintain (Notion, Google Doc, etc.).", 10],
  ]),
  single("q11", "When AI gives you a specific number, statistic, or citation, what do you do?", "verification", [
    ["I trust it and use it.", 0],
    ["I'd probably trust it for low-stakes stuff.", 2],
    ["I verify if it feels important.", 5],
    ["I verify anything specific by default - names, numbers, citations, claims.", 10],
  ]),
  single("q12", "What does \"hallucination\" mean in the context of AI?", "verification", [
    ["I don't know.", 0],
    ["When the AI crashes or errors out.", 1],
    ["When the AI confidently makes something up that isn't true.", 10],
    ["When the AI gets confused and asks for clarification.", 2],
  ]),
  single("q13", "You ask AI for \"5 recent studies on X.\" It gives you 5 with titles, authors, and dates. What do you do?", "verification", [
    ["Use them in my work.", 0],
    ["Skim them and pick the best one.", 2],
    ["Check that at least the first one is real.", 5],
    ["Verify every single one exists before citing any of them.", 10],
  ]),
  single("q14", "Have you ever caught AI giving you something materially wrong (a wrong number, a fake quote, a non-existent tool feature, etc.)?", "verification", [
    ["No, I rarely check or haven't used AI enough to notice.", 0],
    ["Maybe once or twice.", 3],
    ["Yes, multiple times — I expect it now.", 8],
    ["Yes, and I now have a habit of checking everything specific.", 10],
    ["Rarely — I scope tasks carefully and always verify, so I catch it before it becomes a problem.", 9],
  ]),
  single("q15", "How clearly can you name the #1 highest-ROI place AI could help your business right now?", "businessStrategy", [
    ["I have no idea.", 0],
    ["I have a vague sense but couldn't be specific.", 2],
    ["I have 2 or 3 candidates but haven't decided.", 5],
    ["I know exactly - specific task, specific hours saved or revenue gained.", 10],
  ]),
  {
    id: "q16",
    title: "Which of these are real, recurring problems in your business right now? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q16_a", "Slow follow-up with new leads.", 2, "businessStrategy"),
      option("q16_b", "Too much time spent on email.", 2, "businessStrategy"),
      option("q16_c", "Inconsistent content output (blog, social, email).", 2, "businessStrategy"),
      option("q16_d", "Meeting notes and action items never getting captured.", 2, "businessStrategy"),
      option("q16_e", "Customer support eating team time.", 2, "businessStrategy"),
      option("q16_f", "Manual data entry or cleanup.", 2, "businessStrategy"),
      option("q16_g", "Proposals or quotes taking too long to send.", 2, "businessStrategy"),
      option("q16_h", "None of these.", 0, "businessStrategy"),
    ],
  },
  single("q17", "How would you rate your current AI follow-up speed for new inbound leads?", "businessStrategy", [
    ["We don't follow up automatically - it's manual or it doesn't happen.", 0],
    ["We follow up manually within a few hours during business days.", 3],
    ["We have basic automated email follow-up within 30 minutes.", 6],
    ["We respond in under 5 minutes, 24/7, with AI-assisted personalization or a voice agent.", 10],
  ]),
  single("q18", "About how much of your weekly content (email, social, blog) is currently AI-assisted in some way?", "businessStrategy", [
    ["None.", 0],
    ["Less than 25%.", 3],
    ["About half.", 6],
    ["75% or more - AI is in the loop on almost everything we publish.", 10],
  ]),
  single("q19", "When is building a custom AI model or application actually warranted for a small business?", "businessStrategy", [
    ["Most businesses need one to stay competitive.", 0],
    ["I'm not sure what determines whether you need one or not.", 2],
    ["When off-the-shelf tools can't handle a specific, high-volume, high-ROI workflow unique to your business.", 7],
    ["Almost never — off-the-shelf tools plus good prompts and a no-code automation layer solve most use cases for under $100/month.", 10],
  ]),
  single("q20", "Do you currently use any automation platform (Zapier, Make, n8n, etc.)?", "automationTools", [
    ["I don't know what those are.", 0],
    ["I've heard of them but don't use them.", 2],
    ["I have a few basic Zaps or scenarios running.", 5],
    ["I have multi-step automated workflows running in production.", 8],
    ["I have AI-in-the-loop workflows (automation tool calling an AI model).", 10],
  ]),
  single("q21", "How would you describe your familiarity with AI agents (AI that takes actions, not just answers)?", "automationTools", [
    ["Never heard of them.", 0],
    ["Heard the term, don't really know what they do.", 2],
    ["I understand the concept - AI that can browse, send, book, act.", 5],
    ["I've tried one or used a product that includes an agent.", 8],
    ["I have agents running in my business with human review steps.", 10],
  ]),
  single("q22", "Voice AI for lead calling / appointment booking - where are you?", "automationTools", [
    ["Never considered it.", 0],
    ["Considered it, haven't acted.", 3],
    ["Tested or piloted a voice AI tool.", 6],
    ["Voice AI is live in my business handling real calls.", 10],
  ]),
  {
    id: "q23",
    title: "Which of these AI categories do you have actually running in your business (not tried once)? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q23_a", "AI-drafted email replies", 3, "automationTools"),
      option("q23_b", "AI meeting summaries with action items", 2, "automationTools"),
      option("q23_c", "AI-generated first-draft content", 2, "automationTools"),
      option("q23_d", "AI-powered lead routing or qualification", 3, "automationTools"),
      option("q23_e", "Voice AI answering or making calls", 3, "automationTools"),
      option("q23_f", "AI customer support (chat or email)", 3, "automationTools"),
      option("q23_g", "AI data cleanup or reporting", 2, "automationTools"),
      option("q23_h", "None yet.", 0, "automationTools"),
    ],
  },
  single("q24", "Does your team have a written policy on what data can and can't go into AI tools?", "teamPrivacyImplementation", [
    ["No, and I haven't thought about it.", 0],
    ["No, but I've been meaning to.", 2],
    ["Informal - everyone kind of knows.", 4],
    ["Yes, a written one-pager every team member has read.", 10],
  ]),
  {
    id: "q25",
    title: "Which of these have you (or someone on your team) ever pasted into a free AI chat? Check all that apply.",
    type: "multi",
    maxPoints: 10,
    options: [
      option("q25_a", "Client confidential information or contracts under NDA.", 0, "teamPrivacyImplementation"),
      option("q25_b", "Credit card or bank account numbers.", 0, "teamPrivacyImplementation"),
      option("q25_c", "Health information / PHI.", 0, "teamPrivacyImplementation"),
      option("q25_d", "Login credentials, passwords, or API keys.", 0, "teamPrivacyImplementation"),
      option("q25_e", "Proprietary source code from a client.", 0, "teamPrivacyImplementation"),
      option("q25_f", "Internal trade secrets or unannounced plans.", 0, "teamPrivacyImplementation"),
      option("q25_g", "None of these - we're careful.", 10, "teamPrivacyImplementation"),
=======
    2,
  ),
  single(
    "q2",
    'AI tells you: "Ad spend rose 20% and sales rose 20% the same month, so the ads work - every dollar of spend returns a dollar of sales." What\'s the main problem?',
    "verification",
    [
      "Percentages should be shown as decimals.",
      "A matching percentage rise doesn't prove the ads caused the sales, and equal percentages don't mean a dollar-for-dollar return.",
      "20% is too small to matter.",
      "It should have compared to last year.",
    ],
    1,
  ),
  single(
    "q3",
    'A customer review reads: "Fast shipping and the product is solid, though the box was a bit dented." Which AI summary is accurate?',
    "verification",
    [
      '"Customer is happy with shipping and quality; minor complaint about packaging."',
      '"Customer is satisfied overall and would recommend to others."',
      '"Customer had shipping delays but liked the product."',
      '"Customer was unhappy with the product quality."',
    ],
    0,
  ),
  single(
    "q4",
    'Someone prompts "Give me advice on growing my business" and gets a vague, useless answer. Which single change improves the result most?',
    "prompting",
    [
      'Add "please" and "thank you."',
      'Tell it to "be more specific and detailed."',
      "Add what the business is, its size, the specific bottleneck, and what decision a good answer would let them make.",
      "Ask for the answer in bullet points.",
    ],
    2,
  ),
  single(
    "q5",
    "You want AI's help writing a hiring plan. Which prompt produces the best result?",
    "prompting",
    [
      '"Act as a world-class HR expert and write me a hiring plan."',
      '"Write a hiring plan."',
      "\"We're a 6-person agency adding 2 designers in 3 months on a $90k budget. Draft a hiring plan and tell me the biggest risk in my timeline.\"",
      '"Act as the best recruiter in the world and think step by step."',
>>>>>>> dd44680 (modifed files)
    ],
    2,
  ),
  single(
    "q6",
    "For which task is it most acceptable to use AI output with little or no checking?",
    "verification",
    [
      "Brainstorming internal ideas you'll evaluate yourself anyway.",
      "The final figures on a client invoice.",
      "A public statement issued under your company's name.",
      "Summarizing a contract you're about to sign.",
    ],
    0,
  ),
  single(
    "q7",
    "You need 50 personalized outreach messages. Which approach gets all 50 done well with the least of your time?",
    "automationTools",
    [
      "Write all 50 yourself.",
      "Write one strong message and manually rewrite it 50 times.",
      "Write one template with instructions, give AI the 50 contacts' details, generate all at once, then spot-check a sample.",
      "Have AI write one message and send it identically to all 50.",
    ],
    2,
  ),
  single(
    "q8",
    "You want AI to screen inbound job applicants, but you've never defined what a strong applicant looks like. Strongest first move:",
    "teamPrivacyImplementation",
    [
      'Tell AI "build me an applicant screening system."',
      "Upgrade to the most advanced model.",
      "Write out, in your own words, the signals separating a strong applicant from a weak one - then build the screen around those.",
      "Have AI invent the criteria and use them as-is.",
    ],
    2,
  ),
  single(
    "q9",
    "You're deciding where to spend effort. Which task is a waste to put AI on, because the rule never changes?",
    "automationTools",
    [
      "Drafting replies to varied customer questions.",
      "Copying a customer's address from a form into your CRM every time one is submitted.",
      "Summarizing messy meeting notes.",
      "Deciding which leads look most promising.",
    ],
    1,
  ),
  single(
    "q10",
    "You want a system that, with no human touching it, researches a new lead, writes a tailored email, sends it, and books a call if they reply. What does this require, and what's the main risk?",
    "automationTools",
    [
      "One well-crafted prompt; risk is it runs too long.",
      "A bigger context window; risk is it forgets.",
      "An agent that can act across tools with defined permissions; risk is it taking wrong actions with no human review step.",
      "A faster model; risk is cost.",
    ],
    2,
  ),
  single(
    "q11",
    'You ask AI to "summarize this report in 3 bullets and flag any financial risks." It returns a clean, accurate 3-bullet summary. Most important thing to notice?',
    "verification",
    [
      "Whether the bullets are grammatically parallel.",
      "It never flagged the financial risks - AI often silently drops a second instruction.",
      "Whether 3 bullets is enough.",
      "Whether the tone is formal enough.",
    ],
    1,
  ),
  single(
    "q12",
    "AI's draft is 90% right but contains one clearly false claim about your industry. Best next move:",
    "prompting",
    [
      "Accept it and fix the claim yourself later.",
      "Throw it out and start with a brand-new prompt.",
      "Point to the specific false claim, explain why it's wrong, and have it revise the rest intact.",
      'Ask it to "double-check everything."',
    ],
    2,
  ),
  single(
    "q13",
    "Tool A costs $30/month and saves 1 hour a week of admin. Tool B costs $120/month and saves 8 hours a week on your highest-value work. How should you choose?",
    "businessStrategy",
    [
      "Pick A - it's cheaper.",
      "Weigh each tool's cost against the value of the time it frees, not its sticker price.",
      "Pick neither until both are free.",
      "Pick A because $120 is too much for software.",
    ],
    1,
  ),
  single(
    "q14",
    "If you could point AI at only one thing in your business for the biggest return, the best target is:",
    "businessStrategy",
    [
      "Whatever annoys you most.",
      "Whatever a competitor is doing.",
      "A task that's repetitive, high-volume, and follows a learnable pattern.",
      "The most complex, judgment-heavy decision you make.",
    ],
    2,
  ),
  single(
    "q15",
    'You give AI a 20-page report and ask for "the three biggest risks." It returns three - all drawn from the first two pages. Most likely explanation and fix?',
    "aiBasics",
    [
      "The report only has risks on the first two pages.",
      "The AI is lazy; just ask again.",
      "It may be over-weighting the start of a long input; have it work through the report section by section and list risks per section.",
      "You need a newer model.",
    ],
    2,
  ),
];
